from abc import ABC, abstractmethod
from domain.models import LockerEvent, Locker, Compartment, Reservation

class EventStore(ABC):
    @abstractmethod
    def load_all(self) -> list[LockerEvent]: ...
    @abstractmethod
    def load_by_locker(self, locker_id: str) -> list[LockerEvent]: ...
    @abstractmethod
    def append(self, event: LockerEvent) -> int: ...

class Projection(ABC):
    @abstractmethod
    def rebuild(self, event_store: EventStore) -> int: ...
    @abstractmethod
    def apply(self, event: LockerEvent) -> int: ...
    @abstractmethod
    def query_locker(self, locker_id: str) -> Locker | None: ...
    @abstractmethod
    def query_compartment(self, locker_id: str, compartment_id: str) -> Compartment | None: ...
    @abstractmethod
    def query_reservation(self, reservation_id: str) -> Reservation | None: ...